version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: mcp-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
    driver: bridge
